services:
  - type: web
    name: voting-system
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn django-voting-system.wsgi:application"
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: voting-db
          property: connectionString
    deployScript: |
      python manage.py migrate
      python manage.py createsuperuser --noinput --email calix@yahoo.com
